//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeiterfassung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rollen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rollen()
        {
            this.Mitarbeiter = new HashSet<Mitarbeiter>();
        }
    
        public int id_Rollen { get; set; }
        public string kurz_Beschreibung { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> Leserecht { get; set; }
        public Nullable<int> Schreibrecht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mitarbeiter> Mitarbeiter { get; set; }
        public virtual Rechte Rechte { get; set; }
        public virtual Rechte Rechte1 { get; set; }
    }
}
