//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeiterfassung
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp
    {
        public int id_Zeiten { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string BeginnAZ { get; set; }
        public string EndeAZ { get; set; }
        public Nullable<bool> Urlaub { get; set; }
        public Nullable<bool> sonstAbw { get; set; }
        public string AbwGrund { get; set; }
        public Nullable<double> NettoAZ { get; set; }
        public Nullable<int> Pause { get; set; }
    }
}
